// AUTO-GENERATED by scripts/generate-saudi-cities.mjs from
// backend-nest/assets/geo/saudi-cities.json (v2). Do not edit by hand.
// City-centre coordinates are public reference data (no user or listing locations).

export type SaudiCityRegionEntry = { id: string; nameAr: string; nameEn: string; capitalId: string };

export type SaudiCityEntry = {
  id: string;
  regionId: string;
  nameAr: string;
  nameEn: string;
  aliases: string[];
  lat: number;
  lng: number;
};

export const SAUDI_CITIES_VERSION = 2;

export const SAUDI_CITY_REGIONS: SaudiCityRegionEntry[] = [
  {
    "id": "riyadh",
    "nameAr": "منطقة الرياض",
    "nameEn": "Riyadh",
    "capitalId": "riyadh-city"
  },
  {
    "id": "makkah",
    "nameAr": "منطقة مكة المكرمة",
    "nameEn": "Makkah",
    "capitalId": "makkah-city"
  },
  {
    "id": "madinah",
    "nameAr": "منطقة المدينة المنورة",
    "nameEn": "Madinah",
    "capitalId": "madinah-city"
  },
  {
    "id": "qassim",
    "nameAr": "منطقة القصيم",
    "nameEn": "Qassim",
    "capitalId": "buraidah"
  },
  {
    "id": "eastern",
    "nameAr": "المنطقة الشرقية",
    "nameEn": "Eastern",
    "capitalId": "dammam"
  },
  {
    "id": "asir",
    "nameAr": "منطقة عسير",
    "nameEn": "Asir",
    "capitalId": "abha"
  },
  {
    "id": "tabuk",
    "nameAr": "منطقة تبوك",
    "nameEn": "Tabuk",
    "capitalId": "tabuk-city"
  },
  {
    "id": "hail",
    "nameAr": "منطقة حائل",
    "nameEn": "Hail",
    "capitalId": "hail-city"
  },
  {
    "id": "northern",
    "nameAr": "منطقة الحدود الشمالية",
    "nameEn": "Northern Borders",
    "capitalId": "arar"
  },
  {
    "id": "jazan",
    "nameAr": "منطقة جازان",
    "nameEn": "Jazan",
    "capitalId": "jazan-city"
  },
  {
    "id": "najran",
    "nameAr": "منطقة نجران",
    "nameEn": "Najran",
    "capitalId": "najran-city"
  },
  {
    "id": "bahah",
    "nameAr": "منطقة الباحة",
    "nameEn": "Al Bahah",
    "capitalId": "bahah-city"
  },
  {
    "id": "jawf",
    "nameAr": "منطقة الجوف",
    "nameEn": "Al Jawf",
    "capitalId": "sakaka"
  }
];

export const SAUDI_CITIES: SaudiCityEntry[] = [
  {
    "id": "riyadh-city",
    "regionId": "riyadh",
    "nameAr": "الرياض",
    "nameEn": "Riyadh",
    "aliases": [],
    "lat": 24.6389,
    "lng": 46.716
  },
  {
    "id": "diriyah",
    "regionId": "riyadh",
    "nameAr": "الدرعية",
    "nameEn": "Diriyah",
    "aliases": [],
    "lat": 24.7483,
    "lng": 46.5718
  },
  {
    "id": "kharj",
    "regionId": "riyadh",
    "nameAr": "الخرج",
    "nameEn": "Al Kharj",
    "aliases": [
      "السيح"
    ],
    "lat": 24.1483,
    "lng": 47.305
  },
  {
    "id": "dawadmi",
    "regionId": "riyadh",
    "nameAr": "الدوادمي",
    "nameEn": "Ad Dawadmi",
    "aliases": [
      "دوادمي"
    ],
    "lat": 24.5077,
    "lng": 44.3924
  },
  {
    "id": "majmaah",
    "regionId": "riyadh",
    "nameAr": "المجمعة",
    "nameEn": "Al Majmaah",
    "aliases": [],
    "lat": 25.9039,
    "lng": 45.3456
  },
  {
    "id": "quwayiyah",
    "regionId": "riyadh",
    "nameAr": "القويعية",
    "nameEn": "Al Quwayiyah",
    "aliases": [],
    "lat": 24.0651,
    "lng": 45.2844
  },
  {
    "id": "aflaj",
    "regionId": "riyadh",
    "nameAr": "ليلى",
    "nameEn": "Layla",
    "aliases": [
      "الأفلاج",
      "الافلاج"
    ],
    "lat": 22.2929,
    "lng": 46.7172
  },
  {
    "id": "wadi-dawasir",
    "regionId": "riyadh",
    "nameAr": "وادي الدواسر",
    "nameEn": "Wadi ad-Dawasir",
    "aliases": [
      "الخماسين",
      "الدواسر"
    ],
    "lat": 20.4644,
    "lng": 44.7872
  },
  {
    "id": "zulfi",
    "regionId": "riyadh",
    "nameAr": "الزلفي",
    "nameEn": "Az Zulfi",
    "aliases": [],
    "lat": 26.2995,
    "lng": 44.8154
  },
  {
    "id": "shaqra",
    "regionId": "riyadh",
    "nameAr": "شقراء",
    "nameEn": "Shaqra",
    "aliases": [],
    "lat": 25.2402,
    "lng": 45.251
  },
  {
    "id": "hawtat-bani-tamim",
    "regionId": "riyadh",
    "nameAr": "حوطة بني تميم",
    "nameEn": "Hawtat Bani Tamim",
    "aliases": [],
    "lat": 23.496,
    "lng": 46.878
  },
  {
    "id": "afif",
    "regionId": "riyadh",
    "nameAr": "عفيف",
    "nameEn": "Afif",
    "aliases": [],
    "lat": 23.9065,
    "lng": 42.9172
  },
  {
    "id": "ghat",
    "regionId": "riyadh",
    "nameAr": "الغاط",
    "nameEn": "Al Ghat",
    "aliases": [],
    "lat": 26.0286,
    "lng": 44.9508
  },
  {
    "id": "sulayyil",
    "regionId": "riyadh",
    "nameAr": "السليل",
    "nameEn": "As Sulayyil",
    "aliases": [],
    "lat": 20.4607,
    "lng": 45.5779
  },
  {
    "id": "duruma",
    "regionId": "riyadh",
    "nameAr": "ضرماء",
    "nameEn": "Dhurma",
    "aliases": [
      "ضرما"
    ],
    "lat": 24.5955,
    "lng": 46.1337
  },
  {
    "id": "muzahmiyah",
    "regionId": "riyadh",
    "nameAr": "المزاحمية",
    "nameEn": "Al Muzahimiyah",
    "aliases": [],
    "lat": 24.4728,
    "lng": 46.2706
  },
  {
    "id": "rumah",
    "regionId": "riyadh",
    "nameAr": "رماح",
    "nameEn": "Rumah",
    "aliases": [],
    "lat": 25.5697,
    "lng": 47.1567
  },
  {
    "id": "thadiq",
    "regionId": "riyadh",
    "nameAr": "ثادق",
    "nameEn": "Thadiq",
    "aliases": [],
    "lat": 25.2963,
    "lng": 45.8692
  },
  {
    "id": "huraymila",
    "regionId": "riyadh",
    "nameAr": "حريملاء",
    "nameEn": "Huraymila",
    "aliases": [],
    "lat": 25.1258,
    "lng": 46.1286
  },
  {
    "id": "hariq",
    "regionId": "riyadh",
    "nameAr": "الحريق",
    "nameEn": "Al Hariq",
    "aliases": [],
    "lat": 23.6336,
    "lng": 46.5139
  },
  {
    "id": "marat",
    "regionId": "riyadh",
    "nameAr": "مرات",
    "nameEn": "Marat",
    "aliases": [],
    "lat": 25.0717,
    "lng": 45.4572
  },
  {
    "id": "dilam",
    "regionId": "riyadh",
    "nameAr": "الدلم",
    "nameEn": "Ad Dilam",
    "aliases": [],
    "lat": 23.991,
    "lng": 47.1618
  },
  {
    "id": "rayn",
    "regionId": "riyadh",
    "nameAr": "الرين",
    "nameEn": "Ar Rayn",
    "aliases": [],
    "lat": 23.5406,
    "lng": 45.5108
  },
  {
    "id": "sajir",
    "regionId": "riyadh",
    "nameAr": "ساجر",
    "nameEn": "Sajir",
    "aliases": [],
    "lat": 25.1806,
    "lng": 44.6003
  },
  {
    "id": "nifi",
    "regionId": "riyadh",
    "nameAr": "نفي",
    "nameEn": "Nifi",
    "aliases": [],
    "lat": 25.0198,
    "lng": 43.8195
  },
  {
    "id": "bijadiyah",
    "regionId": "riyadh",
    "nameAr": "البجادية",
    "nameEn": "Al Bijadiyah",
    "aliases": [],
    "lat": 24.2963,
    "lng": 43.7414
  },
  {
    "id": "qasab",
    "regionId": "riyadh",
    "nameAr": "القصب",
    "nameEn": "Al Qasab",
    "aliases": [],
    "lat": 25.2957,
    "lng": 45.5234
  },
  {
    "id": "hawtat-sudair",
    "regionId": "riyadh",
    "nameAr": "حوطة سدير",
    "nameEn": "Hawtat Sudayr",
    "aliases": [
      "سدير"
    ],
    "lat": 25.5977,
    "lng": 45.6179
  },
  {
    "id": "tumair",
    "regionId": "riyadh",
    "nameAr": "تمير",
    "nameEn": "Tumayr",
    "aliases": [],
    "lat": 25.7044,
    "lng": 45.8677
  },
  {
    "id": "jalajil",
    "regionId": "riyadh",
    "nameAr": "جلاجل",
    "nameEn": "Jalajil",
    "aliases": [],
    "lat": 25.6798,
    "lng": 45.4515
  },
  {
    "id": "artawiyah",
    "regionId": "riyadh",
    "nameAr": "الأرطاوية",
    "nameEn": "Al Artawiyah",
    "aliases": [],
    "lat": 26.5063,
    "lng": 45.3539
  },
  {
    "id": "uyaynah",
    "regionId": "riyadh",
    "nameAr": "العيينة",
    "nameEn": "Al Uyaynah",
    "aliases": [],
    "lat": 24.9053,
    "lng": 46.3914
  },
  {
    "id": "hayathim",
    "regionId": "riyadh",
    "nameAr": "الهياثم",
    "nameEn": "Al Hayathim",
    "aliases": [],
    "lat": 24.1655,
    "lng": 47.2376
  },
  {
    "id": "makkah-city",
    "regionId": "makkah",
    "nameAr": "مكة المكرمة",
    "nameEn": "Mecca",
    "aliases": [
      "مكة",
      "مكه"
    ],
    "lat": 21.4266,
    "lng": 39.8256
  },
  {
    "id": "jeddah",
    "regionId": "makkah",
    "nameAr": "جدة",
    "nameEn": "Jeddah",
    "aliases": [
      "جده"
    ],
    "lat": 21.5504,
    "lng": 39.1742
  },
  {
    "id": "taif",
    "regionId": "makkah",
    "nameAr": "الطائف",
    "nameEn": "Taif",
    "aliases": [
      "الطايف"
    ],
    "lat": 21.2703,
    "lng": 40.4158
  },
  {
    "id": "qunfudhah",
    "regionId": "makkah",
    "nameAr": "القنفذة",
    "nameEn": "Al Qunfudhah",
    "aliases": [],
    "lat": 19.1417,
    "lng": 41.0797
  },
  {
    "id": "lith",
    "regionId": "makkah",
    "nameAr": "الليث",
    "nameEn": "Al Lith",
    "aliases": [],
    "lat": 20.148,
    "lng": 40.2722
  },
  {
    "id": "rabigh",
    "regionId": "makkah",
    "nameAr": "رابغ",
    "nameEn": "Rabigh",
    "aliases": [],
    "lat": 22.7986,
    "lng": 39.0349
  },
  {
    "id": "jumum",
    "regionId": "makkah",
    "nameAr": "الجموم",
    "nameEn": "Al Jumum",
    "aliases": [],
    "lat": 21.6212,
    "lng": 39.699
  },
  {
    "id": "khulais",
    "regionId": "makkah",
    "nameAr": "خليص",
    "nameEn": "Khulays",
    "aliases": [],
    "lat": 22.1551,
    "lng": 39.3202
  },
  {
    "id": "kamil",
    "regionId": "makkah",
    "nameAr": "الكامل",
    "nameEn": "Al Kamil",
    "aliases": [],
    "lat": 22.264,
    "lng": 39.7982
  },
  {
    "id": "khurmah",
    "regionId": "makkah",
    "nameAr": "الخرمة",
    "nameEn": "Al Khurmah",
    "aliases": [],
    "lat": 21.9081,
    "lng": 42.0318
  },
  {
    "id": "ranyah",
    "regionId": "makkah",
    "nameAr": "رنية",
    "nameEn": "Ranyah",
    "aliases": [],
    "lat": 21.2572,
    "lng": 42.8502
  },
  {
    "id": "turabah",
    "regionId": "makkah",
    "nameAr": "تربة",
    "nameEn": "Turabah",
    "aliases": [],
    "lat": 21.218,
    "lng": 41.6335
  },
  {
    "id": "muwayh",
    "regionId": "makkah",
    "nameAr": "المويه",
    "nameEn": "Al Muwayh",
    "aliases": [],
    "lat": 22.4366,
    "lng": 41.7619
  },
  {
    "id": "maysan",
    "regionId": "makkah",
    "nameAr": "ميسان",
    "nameEn": "Maysan",
    "aliases": [
      "ميسان بني الحارث"
    ],
    "lat": 20.7372,
    "lng": 40.8387
  },
  {
    "id": "adham",
    "regionId": "makkah",
    "nameAr": "أضم",
    "nameEn": "Adham",
    "aliases": [],
    "lat": 20.4497,
    "lng": 40.8791
  },
  {
    "id": "bahrah",
    "regionId": "makkah",
    "nameAr": "بحرة",
    "nameEn": "Bahrah",
    "aliases": [],
    "lat": 21.4013,
    "lng": 39.45
  },
  {
    "id": "zalim",
    "regionId": "makkah",
    "nameAr": "ظلم",
    "nameEn": "Zalim",
    "aliases": [],
    "lat": 22.7234,
    "lng": 42.1687
  },
  {
    "id": "madinah-city",
    "regionId": "madinah",
    "nameAr": "المدينة المنورة",
    "nameEn": "Medina",
    "aliases": [
      "المدينة",
      "المدينه"
    ],
    "lat": 24.4712,
    "lng": 39.6111
  },
  {
    "id": "yanbu",
    "regionId": "madinah",
    "nameAr": "ينبع",
    "nameEn": "Yanbu",
    "aliases": [
      "ينبع البحر"
    ],
    "lat": 24.089,
    "lng": 38.0687
  },
  {
    "id": "ula",
    "regionId": "madinah",
    "nameAr": "العلا",
    "nameEn": "Al Ula",
    "aliases": [],
    "lat": 26.6083,
    "lng": 37.9227
  },
  {
    "id": "mahd",
    "regionId": "madinah",
    "nameAr": "مهد الذهب",
    "nameEn": "Mahd adh Dhahab",
    "aliases": [
      "المهد"
    ],
    "lat": 23.4996,
    "lng": 40.8792
  },
  {
    "id": "hinakiyah",
    "regionId": "madinah",
    "nameAr": "الحناكية",
    "nameEn": "Al Hinakiyah",
    "aliases": [],
    "lat": 24.8797,
    "lng": 40.5153
  },
  {
    "id": "badr",
    "regionId": "madinah",
    "nameAr": "بدر",
    "nameEn": "Badr",
    "aliases": [],
    "lat": 23.78,
    "lng": 38.7907
  },
  {
    "id": "khaybar",
    "regionId": "madinah",
    "nameAr": "خيبر",
    "nameEn": "Khaybar",
    "aliases": [],
    "lat": 25.7025,
    "lng": 39.2933
  },
  {
    "id": "ais",
    "regionId": "madinah",
    "nameAr": "العيص",
    "nameEn": "Al Ays",
    "aliases": [],
    "lat": 25.0636,
    "lng": 38.1085
  },
  {
    "id": "buraidah",
    "regionId": "qassim",
    "nameAr": "بريدة",
    "nameEn": "Buraydah",
    "aliases": [],
    "lat": 26.3317,
    "lng": 43.9717
  },
  {
    "id": "unayzah",
    "regionId": "qassim",
    "nameAr": "عنيزة",
    "nameEn": "Unayzah",
    "aliases": [],
    "lat": 26.0909,
    "lng": 43.9864
  },
  {
    "id": "rass",
    "regionId": "qassim",
    "nameAr": "الرس",
    "nameEn": "Ar Rass",
    "aliases": [],
    "lat": 25.8685,
    "lng": 43.5039
  },
  {
    "id": "mithnab",
    "regionId": "qassim",
    "nameAr": "المذنب",
    "nameEn": "Al Mithnab",
    "aliases": [],
    "lat": 25.8601,
    "lng": 44.2223
  },
  {
    "id": "bukayriyah",
    "regionId": "qassim",
    "nameAr": "البكيرية",
    "nameEn": "Al Bukayriyah",
    "aliases": [],
    "lat": 26.1392,
    "lng": 43.6578
  },
  {
    "id": "badaie",
    "regionId": "qassim",
    "nameAr": "البدائع",
    "nameEn": "Al Badai",
    "aliases": [],
    "lat": 25.9878,
    "lng": 43.7335
  },
  {
    "id": "asyah",
    "regionId": "qassim",
    "nameAr": "الأسياح",
    "nameEn": "Al Asyah",
    "aliases": [],
    "lat": 26.7958,
    "lng": 44.2036
  },
  {
    "id": "nabhaniyah",
    "regionId": "qassim",
    "nameAr": "النبهانية",
    "nameEn": "An Nabhaniyah",
    "aliases": [],
    "lat": 25.8609,
    "lng": 43.0664
  },
  {
    "id": "shimasiyah",
    "regionId": "qassim",
    "nameAr": "الشماسية",
    "nameEn": "Ash Shimasiyah",
    "aliases": [],
    "lat": 26.3183,
    "lng": 44.2631
  },
  {
    "id": "uyun-al-jiwa",
    "regionId": "qassim",
    "nameAr": "عيون الجواء",
    "nameEn": "Uyun al Jiwa",
    "aliases": [
      "الجواء"
    ],
    "lat": 26.4946,
    "lng": 43.6377
  },
  {
    "id": "riyadh-al-khabra",
    "regionId": "qassim",
    "nameAr": "رياض الخبراء",
    "nameEn": "Riyad al Khabra",
    "aliases": [],
    "lat": 26.0548,
    "lng": 43.5581
  },
  {
    "id": "uqlat-assuqur",
    "regionId": "qassim",
    "nameAr": "عقلة الصقور",
    "nameEn": "Uqlat as Suqur",
    "aliases": [],
    "lat": 25.8284,
    "lng": 42.1979
  },
  {
    "id": "dariyah",
    "regionId": "qassim",
    "nameAr": "ضرية",
    "nameEn": "Dariyah",
    "aliases": [],
    "lat": 24.7157,
    "lng": 42.9284
  },
  {
    "id": "dulay-rashid",
    "regionId": "qassim",
    "nameAr": "ضليع رشيد",
    "nameEn": "Dulay Rashid",
    "aliases": [
      "أبانات"
    ],
    "lat": 25.5031,
    "lng": 42.8467
  },
  {
    "id": "khabra",
    "regionId": "qassim",
    "nameAr": "الخبراء",
    "nameEn": "Al Khabra",
    "aliases": [],
    "lat": 26.07,
    "lng": 43.6245
  },
  {
    "id": "qusaybaa",
    "regionId": "qassim",
    "nameAr": "قصيباء",
    "nameEn": "Qusayba",
    "aliases": [],
    "lat": 26.8874,
    "lng": 43.6363
  },
  {
    "id": "dulaymiyah",
    "regionId": "qassim",
    "nameAr": "الدليمية",
    "nameEn": "Ad Dulaymiyah",
    "aliases": [],
    "lat": 26.0286,
    "lng": 43.2742
  },
  {
    "id": "ain-ibn-fuhayd",
    "regionId": "qassim",
    "nameAr": "عين ابن فهيد",
    "nameEn": "Ayn Ibn Fuhayd",
    "aliases": [],
    "lat": 26.7738,
    "lng": 44.2127
  },
  {
    "id": "fuwwarah",
    "regionId": "qassim",
    "nameAr": "الفوارة",
    "nameEn": "Al Fuwwarah",
    "aliases": [],
    "lat": 26.0598,
    "lng": 42.6601
  },
  {
    "id": "quwarah",
    "regionId": "qassim",
    "nameAr": "القوارة",
    "nameEn": "Al Quwarah",
    "aliases": [],
    "lat": 26.7819,
    "lng": 43.4669
  },
  {
    "id": "khasib",
    "regionId": "qassim",
    "nameAr": "الخشيبي",
    "nameEn": "Al Khushaybi",
    "aliases": [],
    "lat": 25.5636,
    "lng": 43.3528
  },
  {
    "id": "dammam",
    "regionId": "eastern",
    "nameAr": "الدمام",
    "nameEn": "Dammam",
    "aliases": [],
    "lat": 26.4368,
    "lng": 50.104
  },
  {
    "id": "ahsa",
    "regionId": "eastern",
    "nameAr": "الأحساء",
    "nameEn": "Al Ahsa (Hofuf)",
    "aliases": [
      "الهفوف",
      "الاحساء",
      "الحسا",
      "الحساء",
      "Hofuf",
      "Al Hofuf"
    ],
    "lat": 25.3697,
    "lng": 49.5865
  },
  {
    "id": "mubarraz",
    "regionId": "eastern",
    "nameAr": "المبرز",
    "nameEn": "Al Mubarraz",
    "aliases": [],
    "lat": 25.41,
    "lng": 49.5808
  },
  {
    "id": "hafr-albatin",
    "regionId": "eastern",
    "nameAr": "حفر الباطن",
    "nameEn": "Hafar Al-Batin",
    "aliases": [
      "حفر"
    ],
    "lat": 28.4328,
    "lng": 45.9628
  },
  {
    "id": "jubail",
    "regionId": "eastern",
    "nameAr": "الجبيل",
    "nameEn": "Jubail",
    "aliases": [],
    "lat": 27.0007,
    "lng": 49.6532
  },
  {
    "id": "qatif",
    "regionId": "eastern",
    "nameAr": "القطيف",
    "nameEn": "Qatif",
    "aliases": [],
    "lat": 26.5586,
    "lng": 50.0087
  },
  {
    "id": "khobar",
    "regionId": "eastern",
    "nameAr": "الخبر",
    "nameEn": "Khobar",
    "aliases": [],
    "lat": 26.304,
    "lng": 50.196
  },
  {
    "id": "dhahran",
    "regionId": "eastern",
    "nameAr": "الظهران",
    "nameEn": "Dhahran",
    "aliases": [],
    "lat": 26.2967,
    "lng": 50.1202
  },
  {
    "id": "khafji",
    "regionId": "eastern",
    "nameAr": "الخفجي",
    "nameEn": "Khafji",
    "aliases": [],
    "lat": 28.4225,
    "lng": 48.4928
  },
  {
    "id": "ras-tanura",
    "regionId": "eastern",
    "nameAr": "رأس تنورة",
    "nameEn": "Ras Tanura",
    "aliases": [],
    "lat": 26.7074,
    "lng": 50.0674
  },
  {
    "id": "abqaiq",
    "regionId": "eastern",
    "nameAr": "بقيق",
    "nameEn": "Abqaiq",
    "aliases": [
      "أبقيق"
    ],
    "lat": 25.9356,
    "lng": 49.6683
  },
  {
    "id": "nairyah",
    "regionId": "eastern",
    "nameAr": "النعيرية",
    "nameEn": "An Nuayriyah",
    "aliases": [],
    "lat": 27.4742,
    "lng": 48.4789
  },
  {
    "id": "qaryat-al-ulya",
    "regionId": "eastern",
    "nameAr": "قرية العليا",
    "nameEn": "Qaryat al Ulya",
    "aliases": [],
    "lat": 27.5514,
    "lng": 47.6957
  },
  {
    "id": "salwa",
    "regionId": "eastern",
    "nameAr": "سلوى",
    "nameEn": "Salwa",
    "aliases": [
      "العديد"
    ],
    "lat": 24.7408,
    "lng": 50.7583
  },
  {
    "id": "qaysumah",
    "regionId": "eastern",
    "nameAr": "القيصومة",
    "nameEn": "Al Qaysumah",
    "aliases": [],
    "lat": 28.3097,
    "lng": 46.1275
  },
  {
    "id": "sarrar",
    "regionId": "eastern",
    "nameAr": "الصرار",
    "nameEn": "As Sarrar",
    "aliases": [],
    "lat": 26.9836,
    "lng": 48.3872
  },
  {
    "id": "safwa",
    "regionId": "eastern",
    "nameAr": "صفوى",
    "nameEn": "Safwa",
    "aliases": [],
    "lat": 26.6485,
    "lng": 49.9467
  },
  {
    "id": "saihat",
    "regionId": "eastern",
    "nameAr": "سيهات",
    "nameEn": "Sayhat",
    "aliases": [],
    "lat": 26.475,
    "lng": 50.0416
  },
  {
    "id": "anak",
    "regionId": "eastern",
    "nameAr": "عنك",
    "nameEn": "Anak",
    "aliases": [],
    "lat": 26.5196,
    "lng": 50.0271
  },
  {
    "id": "abha",
    "regionId": "asir",
    "nameAr": "أبها",
    "nameEn": "Abha",
    "aliases": [],
    "lat": 18.2164,
    "lng": 42.5044
  },
  {
    "id": "khamis",
    "regionId": "asir",
    "nameAr": "خميس مشيط",
    "nameEn": "Khamis Mushait",
    "aliases": [
      "خميس"
    ],
    "lat": 18.3,
    "lng": 42.7333
  },
  {
    "id": "bisha",
    "regionId": "asir",
    "nameAr": "بيشة",
    "nameEn": "Bisha",
    "aliases": [],
    "lat": 20.0005,
    "lng": 42.6052
  },
  {
    "id": "namas",
    "regionId": "asir",
    "nameAr": "النماص",
    "nameEn": "An Namas",
    "aliases": [],
    "lat": 19.1167,
    "lng": 42.1333
  },
  {
    "id": "muhayil",
    "regionId": "asir",
    "nameAr": "محايل عسير",
    "nameEn": "Muhayil",
    "aliases": [
      "محايل"
    ],
    "lat": 18.5464,
    "lng": 42.0489
  },
  {
    "id": "dhahran-aljanub",
    "regionId": "asir",
    "nameAr": "ظهران الجنوب",
    "nameEn": "Dhahran al Janub",
    "aliases": [],
    "lat": 17.6618,
    "lng": 43.5194
  },
  {
    "id": "tathlith",
    "regionId": "asir",
    "nameAr": "تثليث",
    "nameEn": "Tathlith",
    "aliases": [],
    "lat": 19.5333,
    "lng": 43.5
  },
  {
    "id": "sarat-abidah",
    "regionId": "asir",
    "nameAr": "سراة عبيدة",
    "nameEn": "Sarat Abidah",
    "aliases": [],
    "lat": 18.0874,
    "lng": 43.1326
  },
  {
    "id": "rijal-alma",
    "regionId": "asir",
    "nameAr": "رجال ألمع",
    "nameEn": "Rijal Alma",
    "aliases": [],
    "lat": 18.2125,
    "lng": 42.2733
  },
  {
    "id": "balqarn",
    "regionId": "asir",
    "nameAr": "سبت العلايا",
    "nameEn": "Sabt al Alayah",
    "aliases": [
      "بلقرن"
    ],
    "lat": 19.5633,
    "lng": 41.958
  },
  {
    "id": "majaridah",
    "regionId": "asir",
    "nameAr": "المجاردة",
    "nameEn": "Al Majardah",
    "aliases": [],
    "lat": 19.1302,
    "lng": 41.9236
  },
  {
    "id": "birk",
    "regionId": "asir",
    "nameAr": "البرك",
    "nameEn": "Al Birk",
    "aliases": [],
    "lat": 18.2172,
    "lng": 41.5364
  },
  {
    "id": "bariq",
    "regionId": "asir",
    "nameAr": "بارق",
    "nameEn": "Bariq",
    "aliases": [],
    "lat": 18.9297,
    "lng": 41.9295
  },
  {
    "id": "tanomah",
    "regionId": "asir",
    "nameAr": "تنومة",
    "nameEn": "Tanomah",
    "aliases": [],
    "lat": 18.9535,
    "lng": 42.1703
  },
  {
    "id": "tarib",
    "regionId": "asir",
    "nameAr": "طريب",
    "nameEn": "Tarib",
    "aliases": [],
    "lat": 18.5674,
    "lng": 43.2071
  },
  {
    "id": "harjah",
    "regionId": "asir",
    "nameAr": "الحرجة",
    "nameEn": "Al Harjah",
    "aliases": [],
    "lat": 17.9218,
    "lng": 43.3677
  },
  {
    "id": "ahad-rufaidah",
    "regionId": "asir",
    "nameAr": "أحد رفيدة",
    "nameEn": "Ahad Rafidah",
    "aliases": [],
    "lat": 18.1814,
    "lng": 42.8414
  },
  {
    "id": "amwah",
    "regionId": "asir",
    "nameAr": "الأمواه",
    "nameEn": "Al Amwah",
    "aliases": [],
    "lat": 18.714,
    "lng": 43.661
  },
  {
    "id": "tabuk-city",
    "regionId": "tabuk",
    "nameAr": "تبوك",
    "nameEn": "Tabuk",
    "aliases": [],
    "lat": 28.4013,
    "lng": 36.567
  },
  {
    "id": "wajh",
    "regionId": "tabuk",
    "nameAr": "الوجه",
    "nameEn": "Al Wajh",
    "aliases": [],
    "lat": 26.2444,
    "lng": 36.4533
  },
  {
    "id": "duba",
    "regionId": "tabuk",
    "nameAr": "ضباء",
    "nameEn": "Duba",
    "aliases": [
      "ضبا"
    ],
    "lat": 27.3521,
    "lng": 35.6921
  },
  {
    "id": "tayma",
    "regionId": "tabuk",
    "nameAr": "تيماء",
    "nameEn": "Tayma",
    "aliases": [
      "تيما"
    ],
    "lat": 27.6223,
    "lng": 38.5388
  },
  {
    "id": "umluj",
    "regionId": "tabuk",
    "nameAr": "أملج",
    "nameEn": "Umluj",
    "aliases": [],
    "lat": 25.0303,
    "lng": 37.2622
  },
  {
    "id": "haql",
    "regionId": "tabuk",
    "nameAr": "حقل",
    "nameEn": "Haql",
    "aliases": [],
    "lat": 29.2861,
    "lng": 34.9386
  },
  {
    "id": "bad",
    "regionId": "tabuk",
    "nameAr": "البدع",
    "nameEn": "Al Bad",
    "aliases": [],
    "lat": 28.4842,
    "lng": 35.0141
  },
  {
    "id": "hail-city",
    "regionId": "hail",
    "nameAr": "حائل",
    "nameEn": "Hail",
    "aliases": [
      "حايل"
    ],
    "lat": 27.5219,
    "lng": 41.6907
  },
  {
    "id": "baga",
    "regionId": "hail",
    "nameAr": "بقعاء",
    "nameEn": "Baqaa",
    "aliases": [
      "بقعا"
    ],
    "lat": 27.9103,
    "lng": 42.3899
  },
  {
    "id": "shinan",
    "regionId": "hail",
    "nameAr": "الشنان",
    "nameEn": "Ash Shinan",
    "aliases": [],
    "lat": 27.1748,
    "lng": 42.4449
  },
  {
    "id": "hait",
    "regionId": "hail",
    "nameAr": "الحائط",
    "nameEn": "Al Hait",
    "aliases": [],
    "lat": 25.9916,
    "lng": 40.4662
  },
  {
    "id": "sulaymi",
    "regionId": "hail",
    "nameAr": "السليمي",
    "nameEn": "As Sulaymi",
    "aliases": [],
    "lat": 26.2903,
    "lng": 41.3596
  },
  {
    "id": "shamli",
    "regionId": "hail",
    "nameAr": "الشملي",
    "nameEn": "Ash Shamli",
    "aliases": [],
    "lat": 26.8577,
    "lng": 40.3295
  },
  {
    "id": "mawqaq",
    "regionId": "hail",
    "nameAr": "موقق",
    "nameEn": "Mawqaq",
    "aliases": [],
    "lat": 27.384,
    "lng": 41.1763
  },
  {
    "id": "samira",
    "regionId": "hail",
    "nameAr": "سميراء",
    "nameEn": "Samira",
    "aliases": [],
    "lat": 26.4942,
    "lng": 42.1249
  },
  {
    "id": "jubbah",
    "regionId": "hail",
    "nameAr": "جبة",
    "nameEn": "Jubbah",
    "aliases": [],
    "lat": 28.013,
    "lng": 40.9455
  },
  {
    "id": "arar",
    "regionId": "northern",
    "nameAr": "عرعر",
    "nameEn": "Arar",
    "aliases": [],
    "lat": 30.9816,
    "lng": 41.0165
  },
  {
    "id": "rafha",
    "regionId": "northern",
    "nameAr": "رفحاء",
    "nameEn": "Rafha",
    "aliases": [
      "رفحا"
    ],
    "lat": 29.6324,
    "lng": 43.5179
  },
  {
    "id": "turaif",
    "regionId": "northern",
    "nameAr": "طريف",
    "nameEn": "Turaif",
    "aliases": [],
    "lat": 31.6726,
    "lng": 38.6616
  },
  {
    "id": "uwayqilah",
    "regionId": "northern",
    "nameAr": "العويقيلة",
    "nameEn": "Al Uwayqilah",
    "aliases": [],
    "lat": 30.3633,
    "lng": 42.2382
  },
  {
    "id": "linah",
    "regionId": "northern",
    "nameAr": "لينة",
    "nameEn": "Linah",
    "aliases": [],
    "lat": 28.7611,
    "lng": 43.7389
  },
  {
    "id": "jazan-city",
    "regionId": "jazan",
    "nameAr": "جازان",
    "nameEn": "Jazan",
    "aliases": [
      "جيزان"
    ],
    "lat": 16.8947,
    "lng": 42.558
  },
  {
    "id": "sabya",
    "regionId": "jazan",
    "nameAr": "صبيا",
    "nameEn": "Sabya",
    "aliases": [],
    "lat": 17.1502,
    "lng": 42.6215
  },
  {
    "id": "abu-arish",
    "regionId": "jazan",
    "nameAr": "أبو عريش",
    "nameEn": "Abu Arish",
    "aliases": [],
    "lat": 16.9661,
    "lng": 42.8381
  },
  {
    "id": "samtah",
    "regionId": "jazan",
    "nameAr": "صامطة",
    "nameEn": "Samtah",
    "aliases": [],
    "lat": 16.5972,
    "lng": 42.9439
  },
  {
    "id": "harth",
    "regionId": "jazan",
    "nameAr": "الحرث",
    "nameEn": "Al Harth",
    "aliases": [
      "الخوبة"
    ],
    "lat": 16.7887,
    "lng": 43.2219
  },
  {
    "id": "damad",
    "regionId": "jazan",
    "nameAr": "ضمد",
    "nameEn": "Damad",
    "aliases": [],
    "lat": 17.1051,
    "lng": 42.7795
  },
  {
    "id": "raith",
    "regionId": "jazan",
    "nameAr": "الريث",
    "nameEn": "Ar Rayth",
    "aliases": [],
    "lat": 17.6038,
    "lng": 42.8609
  },
  {
    "id": "baish",
    "regionId": "jazan",
    "nameAr": "بيش",
    "nameEn": "Baish",
    "aliases": [],
    "lat": 17.376,
    "lng": 42.5386
  },
  {
    "id": "farasan",
    "regionId": "jazan",
    "nameAr": "فرسان",
    "nameEn": "Farasan",
    "aliases": [],
    "lat": 16.7022,
    "lng": 42.1183
  },
  {
    "id": "dayer",
    "regionId": "jazan",
    "nameAr": "الدائر",
    "nameEn": "Ad Dair",
    "aliases": [
      "الداير"
    ],
    "lat": 17.3385,
    "lng": 43.1329
  },
  {
    "id": "ahad-masarihah",
    "regionId": "jazan",
    "nameAr": "أحد المسارحة",
    "nameEn": "Ahad al Masarihah",
    "aliases": [],
    "lat": 16.7107,
    "lng": 42.9531
  },
  {
    "id": "edabi",
    "regionId": "jazan",
    "nameAr": "العيدابي",
    "nameEn": "Al Idabi",
    "aliases": [],
    "lat": 17.2352,
    "lng": 42.9404
  },
  {
    "id": "aridah",
    "regionId": "jazan",
    "nameAr": "العارضة",
    "nameEn": "Al Aridah",
    "aliases": [],
    "lat": 17.0395,
    "lng": 43.0837
  },
  {
    "id": "darb",
    "regionId": "jazan",
    "nameAr": "الدرب",
    "nameEn": "Ad Darb",
    "aliases": [],
    "lat": 17.7334,
    "lng": 42.2501
  },
  {
    "id": "tuwal",
    "regionId": "jazan",
    "nameAr": "الطوال",
    "nameEn": "At Tuwal",
    "aliases": [],
    "lat": 16.5308,
    "lng": 42.969
  },
  {
    "id": "harub",
    "regionId": "jazan",
    "nameAr": "هروب",
    "nameEn": "Harub",
    "aliases": [],
    "lat": 17.4398,
    "lng": 42.8927
  },
  {
    "id": "najran-city",
    "regionId": "najran",
    "nameAr": "نجران",
    "nameEn": "Najran",
    "aliases": [],
    "lat": 17.4933,
    "lng": 44.1277
  },
  {
    "id": "sharurah",
    "regionId": "najran",
    "nameAr": "شرورة",
    "nameEn": "Sharurah",
    "aliases": [],
    "lat": 17.4908,
    "lng": 47.1126
  },
  {
    "id": "hubuna",
    "regionId": "najran",
    "nameAr": "حبونا",
    "nameEn": "Hubuna",
    "aliases": [],
    "lat": 17.8518,
    "lng": 44.0232
  },
  {
    "id": "yadamah",
    "regionId": "najran",
    "nameAr": "يدمة",
    "nameEn": "Yadamah",
    "aliases": [],
    "lat": 18.5292,
    "lng": 44.2031
  },
  {
    "id": "khubash",
    "regionId": "najran",
    "nameAr": "خباش",
    "nameEn": "Khubash",
    "aliases": [],
    "lat": 17.5499,
    "lng": 44.7411
  },
  {
    "id": "kharkhir",
    "regionId": "najran",
    "nameAr": "الخرخير",
    "nameEn": "Al Kharkhir",
    "aliases": [],
    "lat": 18.8536,
    "lng": 51.1217
  },
  {
    "id": "bahah-city",
    "regionId": "bahah",
    "nameAr": "الباحة",
    "nameEn": "Al Bahah",
    "aliases": [],
    "lat": 20.0138,
    "lng": 41.4656
  },
  {
    "id": "baljurashi",
    "regionId": "bahah",
    "nameAr": "بلجرشي",
    "nameEn": "Baljurashi",
    "aliases": [],
    "lat": 19.8594,
    "lng": 41.5572
  },
  {
    "id": "mandaq",
    "regionId": "bahah",
    "nameAr": "المندق",
    "nameEn": "Al Mandaq",
    "aliases": [],
    "lat": 20.1105,
    "lng": 41.2828
  },
  {
    "id": "mikhwah",
    "regionId": "bahah",
    "nameAr": "المخواة",
    "nameEn": "Al Mikhwah",
    "aliases": [],
    "lat": 19.7794,
    "lng": 41.4356
  },
  {
    "id": "aqiq",
    "regionId": "bahah",
    "nameAr": "العقيق",
    "nameEn": "Al Aqiq",
    "aliases": [],
    "lat": 20.2836,
    "lng": 41.656
  },
  {
    "id": "ghamid-zinad",
    "regionId": "bahah",
    "nameAr": "غامد الزناد",
    "nameEn": "Ghamid az Zinad",
    "aliases": [],
    "lat": 19.5944,
    "lng": 41.5201
  },
  {
    "id": "hajrah",
    "regionId": "bahah",
    "nameAr": "الحجرة",
    "nameEn": "Al Hajrah",
    "aliases": [],
    "lat": 20.2333,
    "lng": 41.05
  },
  {
    "id": "sakaka",
    "regionId": "jawf",
    "nameAr": "سكاكا",
    "nameEn": "Sakakah",
    "aliases": [],
    "lat": 29.9697,
    "lng": 40.2064
  },
  {
    "id": "qurayyat",
    "regionId": "jawf",
    "nameAr": "القريات",
    "nameEn": "Al Qurayyat",
    "aliases": [],
    "lat": 31.3333,
    "lng": 37.3419
  },
  {
    "id": "dumat-aljandal",
    "regionId": "jawf",
    "nameAr": "دومة الجندل",
    "nameEn": "Dumat al Jandal",
    "aliases": [],
    "lat": 29.8148,
    "lng": 39.8572
  },
  {
    "id": "tabarjal",
    "regionId": "jawf",
    "nameAr": "طبرجل",
    "nameEn": "Tabarjal",
    "aliases": [],
    "lat": 30.4999,
    "lng": 38.216
  },
  {
    "id": "hadithah",
    "regionId": "jawf",
    "nameAr": "الحديثة",
    "nameEn": "Al Hadithah",
    "aliases": [],
    "lat": 31.4544,
    "lng": 37.1589
  },
  {
    "id": "suwayr",
    "regionId": "jawf",
    "nameAr": "صوير",
    "nameEn": "Suwayr",
    "aliases": [],
    "lat": 30.1173,
    "lng": 40.3888
  }
];
